apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: waifu-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: waifu-app
        tier: frontend
        track: stable
    spec:
      containers:
      - args:
        - nginx
        - -g
        - daemon off;
        image: us.gcr.io/waifuwebapp/client
        name: client
        ports:
        - containerPort: 80
      hostname: waifu-app