version: '3'
services:

# Setup node container
  server:
    build: ./waifu-server
    hostname: ${SERVER_ALIAS}
    expose:
      - ${SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm start

# Setup client container
  client:
    build: ./waifu-app
    hostname: waifu-app
    environment:
      - REACT_APP_API_HOST=http://${SERVER_ALIAS}:${SERVER_PORT}/
      - REACT_APP_PORT=${APP_PORT}
    expose:
      - ${APP_PORT}
    ports:
      - ${MAP_APP_PORT}:${APP_PORT}
    links:
      - server
    command: [nginx, '-g', 'daemon off;']