version: '3'
services:


# Setup mongodb container
  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --port 27017

# Setup redis container
  redis:
    image: redis:latest
    hostname: redis
    command: redis-server

# Setup node container
  server:
    build: ./waifu-server
    hostname: waifu-server
    expose:
      - 3001
    environment:
      DB_HOST: mongodb
      API_PORT: 3001
      REDIS_HOST: redis
    ports:
      - 3001:3001
    links:
      - mongodb
      - redis
    command: npm start

# Setup client container
  client:
    build: ./waifu-app
    hostname: waifu-app
    environment:
      - REACT_APP_API_HOST=http://waifu-server:3001/
      - REACT_APP_PORT=80
    expose:
      - 80
    ports:
      - 8000:80
    links:
      - server
    command: [nginx, '-g', 'daemon off;']