version: '3'
services:
# Setup node container
server:
  build: ./waifu-server
  expose:
    - 3001
  #environment:
  #  API_HOST: ${API_HOST}
  #  APP_SERVER_PORT: ${APP_SERVER_PORT}
  ports:
    - 3001:3001
  #volumes:
  #  - ./server/src:/usr/src/app/
  command: npm start
# Setup client container
client:
  build: ./waifu-app
  #environment:
  #  - REACT_APP_PORT=${REACT_APP_PORT}
  expose:
    - 80
  ports:
    - 80:8000
  #volumes:
  #  - ./client/src:/usr/src/app/src
  #  - ./client/public:/usr/src/app/public
  links:
    - server
  command: npm start