apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: waifu-app
      tier: database
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: waifu-app
        tier: database
        track: stable
    spec:
      containers:
      - args:
        - mongod
        - --port
        - "27017"
        env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo:latest
        name: mongodb
      hostname: mongodb