apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: waifu-app
      tier: cache
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: waifu-app
        tier: cache
        track: stable
    spec:
      containers:
      - args:
        - redis-server
        image: redis:latest
        name: redis
      hostname: redis