apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: waifu-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: waifu-app
        tier: backend
        track: stable
    spec:
      containers:
      - args:
        - npm
        - start
        image: us.gcr.io/waifuwebapp/server:latest
        env:
            - name: NODE_ENV
              value: 'production'
        name: server
        ports:
        - containerPort: 3001
      hostname: server